language: java
jdk:
  - oraclejdk8
notifications:
  email: false
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
after_success:
  - mvn clean test jacoco:report coveralls:report